src/react/Pages/Login.jsx, src/react/Pages/NotFound.jsx, src/react/Pages/Pay.jsx, src/react/Pages/PaymentInfo.jsx
Because name of this app is BunqDesktop and not BunqWeb :-)
=> Change titles to BunqDesktop

src/background.js, src/react/Actions/accounts.js, src/react/Actions/pay.js, src/react/Actions/payment_info.js, src/react/Actions/payments.js, src/react/Actions/request_inquiries.js, src/react/Actions/request_inquiry.js, src/react/Actions/user.js, src/react/Actions/users.js, src/react/Components/Header.jsx, src/react/Components/Layout.jsx, src/react/Components/MainDrawer.jsx, src/react/Helpers/BunqErrorHandler.js, src/react/Pages/ApplicationInfo.jsx, src/react/Pages/Dashboard/PaymentListItem.jsx, src/react/Pages/Pay.jsx, src/react/Pages/PaymentInfo.jsx, src/react/Pages/RequestInquiry.jsx, src/react/Pages/RequestInquiry/MinimumAge.jsx, src/react/Pages/RequestInquiry/RedirectUrl.jsx, src/react/Pages/RequestInquiry/RequestInquiry.jsx, src/react/Pages/RequestInquiry/TargetSelection.jsx, src/react/Reducers/index.js, src/react/Reducers/request_inquiries.js, src/react/Reducers/request_inquiry.js, src/react/Routes.jsx, src/scss/partials/base.scss
Added the request inquiry page and other minor changes throughout the project
=> Request inquiry

src/background.js, src/helpers/touchbar.js, src/react/Components/Layout.jsx
To add some cool features it's nice to have MacOS touchbar support.
- Added touchbar.js in the helpers folder
- Added buttons to switch pages
=> Touchbar support

src/react/Actions/user.js, src/react/Components/AccountList/AccountList.jsx, src/react/Components/CombinedList.jsx, src/react/Helpers/Utils.js, src/react/Pages/MasterCardActionInfo.jsx, src/react/Pages/PaymentInfo.jsx, src/react/Pages/RequestInquiryInfo.jsx, src/react/Pages/RequestResponseInfo.jsx
In the current release some dates are parsed wrongly which resolves into payments being in the wrong date group.
closes #82
=> Invalid group date payment overview

src/react/Actions/registration.js, src/react/Pages/LoginPassword.jsx, src/react/Reducers/registration.js
In the current release you are always prompted for a password on startup even if you don't have a password setup. 
#83
=> Login without password

src/react/Components/ListItems/BunqMeTabListItem.jsx
=> Show number of payments for bunq.me Tab

.travis.yml
Fixed release script for travis
=> Release 0.8.7

.travis.yml, bunqdesktop.nuspec, chocolatey/chocolateyInstall.ps1, package.json, src/react/Helpers/GetShareDetailBudget.js
=> Release 0.8.9

src/react/Pages/Dashboard.jsx, src/react/Pages/Pay.jsx
=> Release 0.8.10

bunqdesktop.nuspec, chocolatey/chocolateyInstall.ps1, package.json, src/react/Pages/Pay.jsx, yarn.lock
- Fixed a bug with the formatting of datepickers
=> Release 0.8.11

src/react/Components/Header.jsx, src/react/Locales/en.json
Added a notification in the header which shows when you are in sandbox-mode:
=> Show banner when in sandbox mode

src/react/Locales/en.json, src/react/Pages/LoginPassword.jsx
Should help with #268.
Although this only works onKeyPress since it's an event-driven check.
=> Add a notification if we detected capslock on login-screen

src/react/Pages/RequestInquiry/RequestInquiry.jsx, src/react/Pages/ScheduledPayments/ScheduledPaymentsEditDialog.jsx
- Closes bunqCommunity/bunqDesktop#272
=> Add multiline support in descriptions

src/react/Components/AccountCard.jsx
Fixes #336 
- You missed one on Account Card ;)
=> Also format Iban on Account Card

.travis.yml
Previous release wasn't uploaded correctly due to typos in the travis configuration
=> Release 0.9.0 correction

src/react/Pages/Pay/Pay.jsx
=> Fixed "insufficient funds" warning for scheduled payments

bunqdesktop.nuspec, chocolatey/chocolateyInstall.ps1, package.json, src/react/Pages/Connect/Connect.jsx
Fix a bug where the connect page was using the default account Id during connect requests
=> Release 0.9.3

bunqdesktop.nuspec, chocolatey/chocolateyInstall.ps1, package.json, src/react/Actions/registration.js
- Fix a bug where keys weren't correctly stored on the device during login.
=> Release 0.9.4

src/react/Functions/EventStatusTexts.js, src/react/WebWorkers/stats.worker.js
=> Display Google Pay payments as such instead of Tap & Pay

.travis.yml
No need to keep pulling images, here's a way to cache docker images :)
Source: https://stackoverflow.com/a/58505735
=> build: cache docker images

src/react/Functions/EventStatusTexts.js
Add support for top up payment labels.
=> feat: support CHECKOUT_MERCHANT payment labels
